version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/freshwater.content
    environment:
      ADDONS: "freshwater.content[test]"
      DEVELOP: "src/freshwater.content"
